#GLOBAL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/QuarkusSocial

#quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.log.category."org.hibernate.SQL".level=DEBUG
quarkus.log.category."org.hibernate.tool.schema".level=DEBUG

quarkus.swagger-ui.always-include=true

#TEST
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=sa
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:quarkus-social

#quarkus.hibernate-orm.database.generation=update
%test.quarkus.log.category."org.hibernate.SQL".level=DEBUG
%test.quarkus.log.category."org.hibernate.tool.schema".level=DEBUG
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.quarkus.hibernate-orm.log.sql=true
